### ISSUE TITLE
icons not showing in ObservationTypes

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#2]
and the syncing of Observations does not seem to work. I get a triangle with exclamation point in Outbox after syncing arrow revolves.

**Comment by sheppard** [comment]
Yes, I neglected to actually put the icon into the template.  It shouldn't be too hard to mimic Try WQ's [campaign list](https://github.com/powered-by-wq/try.wq.io/blob/master/templates/campaign_list.html) to get it there.

If you tap a failing item in the outbox it should open the form with the error message at the bottom.

**Comment by managingwholes** [comment]
I put the icon in the template and ran deploy.sh. Icons still not showing up, though they are uploaded and seemingly correctly referenced in the html.

**Comment by sheppard** [comment]
Hmm - the difference is whether icons (and other images) are referenced by their full URL (default) or by just the path relative to `/media/` (which is how Try WQ is configured).  You can disable full URLs like this (c.f. [Try WQ's settings.py](https://github.com/powered-by-wq/try.wq.io/blob/v0.1.1/db/trywq/settings.py#L75)):

``` python
REST_FRAMEWORK['UPLOADED_FILES_USE_URL'] = False
```

Full URLs theoretically make more sense, but it's easier to turn them off if we end up integrating the [thumbnailer](https://github.com/wq/django-media-thumbnailer).  The thumbnailer relies on the partial paths so it can prepend the thumbnail size as a part of the URL (as can be seen in Try WQ's [thumbnail template](https://github.com/powered-by-wq/try.wq.io/blob/master/templates/partials/photo_thumbnail.html)).

The general question is whether the thumbnailer should be enabled in the default template, which would also imply that this setting should be set to False by default - see wq/wq-django-template#22.

**Comment by managingwholes** [comment]
Not sure I understand the relevant considerations here, or what to do.

**Comment by sheppard** [comment]
The issue is that the Try WQ example assumes full upload URLs are turned off, whereas this project (currently) has them on.

So,

``` javascript
// /observationtypes.json with UPLOADED_FILES_USE_URL = True
[
  {
    "id": 1,
    "icon": "https://atlasbiowork.com/media/forms/logo.png"
  }
]
```

plus

``` html
<!-- observationtype_list.html with media prefix -->
<img src="/media/{{icon}}">
```

becomes

``` html
<!-- /observationtypes/ output html -->
<img src="/media/https://atlasbiowork.com/media/forms/logo.png">
```

which is an invalid URL.

The fix is to either remove the `/media/` prefix (and keep the full URLs):

``` html
<!-- observationtype_list.html without media prefix -->
<img src="{{icon}}">
```

``` html
<!-- /observationtypes/ output html -->
<img src="https://atlasbiowork.com/media/forms/logo.png">
```

or to update `REST_FRAMEWORK['UPLOADED_FILES_USE_URL'] = False` (and keep the `/media/` prefix):

``` javascript
// /observationtypes.json with UPLOADED_FILES_USE_URL = False
[
  {
    "id": 1,
    "icon": "forms/logo.png"
  }
]
```

``` html
<!-- /observationtypes/ output html -->
<img src="/media/forms/logo.png">
```

The choice of which approach to take largely depends on whether we eventually want to use the thumbnailer - we probably do, so it would make sense to use the UPLOADED_FILES_USE_URL = False approach.

**Comment by managingwholes** [comment]
So, I need to add this line to settings.py??

REST_FRAMEWORK['UPLOADED_FILES_USE_URL'] = False

**Comment by sheppard** [comment]
Yes, that should do the trick.

**Comment by managingwholes** [comment]
Now it appears we need the thumbnailer or something, as the list of observations displays broken links to the associated photos.

**Comment by sheppard** [comment]
The observations list is still expecting full URLs.  We could just add the `/media/` prefix, but we might as well incorporate the thumbnailer while we're at it.

``` bash
sudo pip3 install https://github.com/wq/django-media-thumbnailer/archive/master.zip
```

``` python
# urls.py
urlpatterns = patterns('',
     url(r'^admin/', include(admin.site.urls)),
     url(r'^generate/', include('dmt.urls')), # thumbnailer
```

``` apacheconf
# atlasbiowork.conf
RewriteEngine On
RewriteCond /var/www/atlasbiowork%{REQUEST_FILENAME} !-f
RewriteCond /var/www/atlasbiowork/media/$2 -f
RewriteRule ^/media/([^\/]+)/(.+) /generate/$1/$2 [PT]
```

``` html
<!-- observation_list.html -->
<li>
  <a href="{{rt}}/observations/{{id}}">
    {{#files}}{{^@index}}
    <img src="/media/160/{{file}}" alt="{{label}}">
    {{/@index}}{{/files}}
    <h3>{{label}}</h3>
```

**Comment by managingwholes** [comment]
OK, got this, and had to install mod rewrite of course.

Now the observation list has the thumbnails, but when you view an observation, the photo link is broken. It might be best here to display the full picture, not the thumbnail. Currently we have in observation_detail.html

<img src = "{{file}}"  
and this is showing an incomplete URL e.g. <img src="images/Jellyfish.jpg"

Would be best if observation_edit.html would show the full photo as well, along with the option of changing the photo.

so, needing a bit of advice on changing this . . .

**Comment by sheppard** [comment]
To save on network traffic, I usually use larger thumbnails for the detail view, but you can use the original image as well.  Either

``` html
<img src="/media/1024/{{file}}">
```

or

``` html
<img src="/media/{{file}}">
```

should do the trick.

You can add the image to the edit.html as well - though there are some issues with how images are saved for existing items (see #10).

**Comment by managingwholes** [comment]
For observation_edit.html the template shows <img src = "{{image_url}}" and the edit page displays an empty string for the img src tag. Could we display the 1024 thumbnail here, and what would be the consequences for the edit functionality? It would be good to give the option of uploading a new image.
