### ISSUE TITLE
support for multiple photos

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#24]
Want to be able to configure an observationtype with multiple photos (this may relate also to nested subobservations).

**Comment by sheppard** [comment]
This should be working now that #4 and #7 are fixed.

**Comment by sheppard** [comment]
Here's the XLSForm I'm using to test:
[repeat.xlsx](https://github.com/Soil-Carbon-Coalition/atlasbiowork/files/200142/repeat.xlsx)
