### ISSUE TITLE
observation detail template

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#26]
Would like to enlarge photo display on observation detail template

atlasbiowork/templates/observation_detail.html

and am confused as template tag for photo is outside the table yet on the page it appears inside the table.

**Comment by sheppard** [comment]
The template tag for files in observation_detail.html is no longer applicable - I neglected to remove it with #7.  The new template tag is defined in xlsconv_templates/detail.html and saved with each ObservationType's detail_html.
