### ISSUE TITLE
ordering of observation list

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#29]
would like to change order in which observations are listed, to most recently posted first. How and where would I do this? In the observation serializer?

**Comment by sheppard** [comment]
You can change the default ordering on the model itself with a [`Meta` attribute](https://docs.djangoproject.com/en/1.10/ref/models/options/#ordering):

``` python
class Observation(models.Model):

    # (existing code...)

    class Meta:
        ordering = ['-pk'] # or ['-entered']
```
