### ISSUE TITLE
cannot specify new site on Android

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#5]
Tried with my Samsung phone this morning and tried to enter a new site. Could not place a point, and app did not seem to connect with my gps or locate me. All I saw was site name, accuracy, and a map on which I could not place a point. With my laptop, I was able to place a point.

The default behavior for New site should be locating the user, much as try.wq.io does, giving option of GPS lookup, point on map, or enter coordinates.

**Comment by managingwholes** [comment]
Using developer console, I get this error in atlasbiowork/sites/new. Is it the double slash in the first line?

`atlasbiowork.js?v=.03:9664 GET https://atlasbiowork.com/sites//edit.geojson 404 (Not Found)send @ atlasbiowork.js?v=.03:9664jQuery.extend.ajax @ atlasbiowork.js?v=.03:9215json.get @ atlasbiowork.js?v=.03:28906map.loadLayer @ atlasbiowork.js?v=.03:43594(anonymous function) @ atlasbiowork.js?v=.03:43694map.createOverlay @ atlasbiowork.js?v=.03:43674map.createMap @ atlasbiowork.js?v=.03:43911map.run @ atlasbiowork.js?v=.03:43475(anonymous function) @ atlasbiowork.js?v=.03:33061
atlasbiowork.js?v=.03:43697 Ignoring empty or malformed GeoJSON result.`

**Comment by sheppard** [comment]
The broken map for "New Site" was hopefully addressed in #21.

As for the default behavior, currently you have to do "New Site + Observation" to get the [wq/locate.js](https://wq.io/docs/locate-js) interface, but "New Site" to get the [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) interface.  We can explore combining these into a unified interface at some point.

I made a quick fix in wq.app for the double slash issue (see wq/wq.app#64), though it wasn't the primary cause of this bug.

**Comment by managingwholes** [comment]
When I try to add an Observation to an existing site, I get a 500. I can give you credentials to explore this today.
