### ISSUE TITLE
xls file

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#6]
I tried adding an Observation Type by uploading an xls file, leaving the other two fields blank as instructed, and got a Server error (500), both from the app and from the admin interface. Am I missing something? How did you get yours uploaded?

Also, what might be the "type" (first column in xls) for a photo?

**Comment by sheppard** [comment]
There was likely an error parsing the file.  To avoid the 500 error, I wrapped the parse statement in a try/except clause to catch it.  The error message should now get saved to the HTML field instead of causing the save to fail.

**Comment by sheppard** [comment]
For now only the predefined photo field at the top of every form will actually save to the database.  You can specify "photo" or "image" as the XLSform type to create a space for an additional field, but it won't actually go anywhere (for now, see #7).
